browser: chrome
browser_options: add_argument("--ignore-certificate-errors");add_argument("window-size=1920,1024");add_argument('--no-sandbox');add_argument('--disable-gpu')
environment: default
screenshot: false
AUT_URL: <<OpenshiftClusterURL>>
